### PR TITLE
Fix truncate symbol length

### PR DESCRIPTION
**Pull request by princejwesley**
Truncate symbol length is 3.

### CODE REVIEW

**Comment by princejwesley** [comment]
Question: what if the domain name is lengthier than given length

**Comment by schnittstabil** [comment]
As far as I can see, the following should hold:

``` js
TRUNCATE_SYMBOL_LENGTH == '…/'.length // == 2
```

That's because `…` ([Ellipsis](https://en.wikipedia.org/wiki/Ellipsis)) is a single unicode character.

**Comment by sindresorhus** [comment]
Yup, current is correct. It's helpful to also submit a failing test to prove your change is correct.

**Comment by sindresorhus** [comment]
> Question: what if the domain name is lengthier than given length

Discussed at https://github.com/sindresorhus/humanize-url/issues/1#issuecomment-139407068. Would appriciate some opinions there ;)

**Comment by princejwesley** [comment]
@schnittstabil Sorry, there was an off by one error([#3](https://github.com/sindresorhus/truncate-url/pull/3))

**Pull request closed without merging**
